export const TIPO_INCIDENCIA = {
  FALLA_MASIVA: "FALLA MASIVA",
  FALLA_PUNTUAL: "FALLA PUNTUAL",
  VENTANA_MANTENIMIENTO: "VENTANA DE MANTENIMIENTO"
}


export const CATEGORIA_RED = [
  "ACCESO",
  "AMBIENTE",
  "COMPONENTES",
  "CORE",
  "IT",
  "TRANSPORTE"
] 


export const TICKET_STATUS = {
  EN_GESTION: 'en_gestion'
}


export const TIPO_SERVICIO = {
  DOG: "DOG",
  INTERNET: "INTERNET",
  METROLAN: "METROLAN",
  RBS: "RBS",
  REDES_COMPARTIDAS: "REDES_COMPARTIDAS",
  UI: "UI"
}


export const NIVEL_SEVERIDAD = [
  "BAJO ", 
  "MEDIO",
  "ALTO"
] 

export const TIPO_CLIENTE = {
  BANCA: "BANCA", 
  CARRIER: "CARRIER",   
  CORPORATIVO: "CORPORATIVO", 
  RESIDENCIAL: "RESIDENCIAL"
}


export const CATEGORIA = {
  TIPO_CLIENTE: 'TIPO_CLIENTE',
  PROVEEDOR: 'PROVEEDOR',
  ESTADO: 'ESTADO',
  CIUDAD: 'CIUDAD',
  LOCALIDAD: 'LOCALIDAD',
  CATEGORIA_RED: 'CATEGORIA_RED',
  SUBCATEGORIA: 'SUBCATEGORIA',
  DETALLE: 'DETALLE',
  CAUSA_RAIZ: 'CAUSA_RAIZ',
  SOLUCION_CASO: 'SOLUCION_CASO',
} as const;

export type CategoriaType = typeof CATEGORIA[keyof typeof CATEGORIA];