export const TIPO_INCIDENCIA = {
  FALLA_MASIVA: "FALLA MASIVA",
  FALLA_PUNTUAL: "FALLA PUNTUAL",
  VENTANA_MANTENIMIENTO: "VENTANA DE MANTENIMIENTO"
}


export const CATEGORIA_RED = [
  "ACCESO",
  "AMBIENTE",
  "COMPONENTES",
  "CORE",
  "IT",
  "TRANSPORTE"
] 


export const TICKET_STATUS = {
  EN_GESTION: 'en_gestion'
}


export const TIPO_SERVICIO = {
  DOG: "DOG",
  INTERNET: "INTERNET",
  METROLAN: "METROLAN",
  RBS: "RBS",
  REDES_COMPARTIDAS: "REDES_COMPARTIDAS",
  UI: "UI"
}